---
version: 2
sources:
- name: "deeptanshu.default"
  database: "deeptanshu"
  schema: "default"
  tables:
  - name: "t1"
    description: "Customer location and status information, aiding in tracking customer\
      \ activity and engagement over time."
    columns:
    - name: "customer_id"
      description: "Unique identifier for each customer."
      dataType:
        type: "Bigint"
    - name: "name"
      description: "Full name of the customer."
      dataType:
        type: "String"
    - name: "email"
      description: "Email address of the customer."
      dataType:
        type: "String"
    - name: "city"
      description: "City where the customer resides."
      dataType:
        type: "String"
    - name: "status"
      description: "Current status of the customer's account."
      dataType:
        type: "String"
    - name: "valid_from"
      description: "Start date from which the record is considered valid."
      dataType:
        type: "Date"
    - name: "valid_to"
      description: "End date until which the record remains valid."
      dataType:
        type: "Date"
    - name: "is_current"
      description: "Indicates if the record is currently active."
      dataType:
        type: "Boolean"
    type: "table"
- name: "main.default"
  database: "main"
  schema: "default"
  tables:
  - name: "swee"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "name"
      dataType:
        type: "String"
    - name: "email"
      dataType:
        type: "String"
    - name: "city"
      dataType:
        type: "String"
    - name: "status"
      dataType:
        type: "String"
    - name: "valid_from"
      dataType:
        type: "Date"
    - name: "valid_to"
      dataType:
        type: "Date"
    - name: "is_current"
      dataType:
        type: "Boolean"
    type: "table"
